# -*- coding: utf-8 -*-
"""Web Scraping con Python-semillasperu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eEdfxSBoV-mozrLgXrwc5KMIEdEtEWnE
"""

#Importante descargar las librerías en el cmd con pip install (nombre de librería) antes de ejecutar
#Importanción de librerías, especificamente BeaituflSoup
#que se usa para el web scraping

import pandas as pd
from requests import get
from bs4 import BeautifulSoup
import re
from datetime import datetime

#Lectura de página web

website = "http://genebankperu.inia.gob.pe/consulta?type=6&var=36"
response = get(website)
mysoup = BeautifulSoup(response.text, 'html.parser')

#Identificar la tabla en el código fuente de la página, importante saber un poco o lo básico de la nomenclatura de html, con algunos videos se puede guiar e inferir el uso de términos.

semillas = mysoup.find_all("div" , class_= "dataTables_wrapper dt-bootstrap4")

tabla_semillas = mysoup.find("div", id="example1_wrapper")

tabla_semillas = mysoup.find("div", class_="dataTables_wrapper dt-bootstrap4")
tabla_semillas

#comvertir en a string (tipo cadena) 
tabla_semillas = str (tabla_semillas)

#cambiando caracteres, osea quitar los separadores, reemplazar simbolo y el upper para ponerlo en mayuscula
tabla_semillas = re.sub(r'<.*?>', lambda g: g.group(0).upper(), tabla_semillas)
tabla_semillas

#leyendo la información y guardando en un dataframe
df = pd.read_html(tabla_semillas)[0]
df.head()